### ISSUE TITLE
issue: webpy with the last version Chrome

### ISSUE THREAD

**Issue by liangguang621** [Petersonjoe/BI_Visualization_demo#2]
It can not be work very well with the last version Chrome ( version == 63.0.3239.132 ), but it can work successfully on the Chrome with before version.

**Comment by liangguang621** [comment]
It can work on Firefox or IE explore successfully.

**Comment by Petersonjoe** [comment]
Well..., the 'Cookie' problem exists, this is a web.py frame problem. You could keep an eye on web.py's upgrade.
